### ISSUE TITLE
New: Группа Вк

### ISSUE THREAD

**Issue by xCoDiS** [GishReloaded/Gish-Code-1.12.2#10]
Начну с того что создана группа вк
https://vk.com/gishcode
Закончу вопросом: Надо ли продолжать / отдавать вам эту группу ?
Или вообще закрыть...

**Comment by GishReloaded** [comment]
Я не знаю. Мне это не особо важно.
Группа уже есть у меня. Она не посвящена конкретно этому читу, там просто всякое дерьмо выкладываю.
https://vk.com/deadlycodes
