### ISSUE TITLE
Парочка "новых" функций которые бы хотелось видеть

### ISSUE THREAD

**Issue by xCoDiS** [GishReloaded/Gish-Code-1.12.2#11]
Как обычно это SafeWalk - безопасная прогулка.. Тот же скаффолд (AAC) только без строительства..
Хотелось бы функцию Parkour - авто прыжок на максимально возможное расстояние..
И под конец Было бы не плохо функция AuroFish - Авто Рыбалка.. Кинул удочку и ушел афк..

**Comment by xCoDiS** [comment]
Можно еще 1 мини функцию это NoPush на серверах 1.12.2 вас не отталкивают игроки и мобы.
Возможно это сложно и долго (скорее всего) но это будет только плюсом вашего клиента!
Еще раз спасибо за то что не оставляете ваш софт без обновлений!.

**Comment by xCoDiS** [comment]
И на популярных серверах 3/5 функцию GuiMove обнаруживают. Чаще во время спринта или прыжка. (просто на заметку)

**Comment by GishReloaded** [comment]
Любые недоработки и идеи приветствуются. Спасибо, такие люди как вы помогают сделать чит лучше.

**Comment by Pro100TToRussia** [comment]
Сделайте пожалуйста функцию HitBox,также будет полезна функция FastPlace,желательно сделать функцию AntiXRay как в ClownClient,можно обновить AimBot,так чтоб можно было настроить на сколько человек он агрится.

**Comment by xCoDiS** [comment]
Чтобы высказать свое мнение (идею) нужно каждый раз создавая новый раздел или высказывать его здесь?
Крч: Закрывать или оставить раздел?

**Comment by GishReloaded** [comment]
Im created issue for ideas - https://github.com/GishReloaded/Gish-Code-1.12.2/issues/12
