### ISSUE TITLE
Questions VERY IMPORTAINT

### ISSUE THREAD

**Issue by XeonLyfe** [GishReloaded/Gish-Code-1.12.2#14]
Can I use this source and mish mash it with my coding skills to make my own client
English: Can I use the source code to make my own client

**Comment by ghost** [comment]
it's open source skidder duh

**Comment by Gav06** [comment]
:monkey:

**Comment by dest4590** [comment]
🐒

**Comment by XeonLyfe** [comment]
jesus this is old as fuck lmao
