### ISSUE TITLE
Settings Issue(Crash)

### ISSUE THREAD

**Issue by Ace8Underscore** [GishReloaded/Gish-Code-1.12.2#2]
After messing around with the code I’ve noticed if making a setting in a pre-existing module will result in a game crash leaving me to having to delete the config so the config will be generated with the Boolean setting and not crash. I’ve noticed that if I do continue to change version numbers for my public releases the users won’t notice this but, this would lead them to getting a config that has been reset every next update. Also I’ve noticed it does slow me down in testing it in my ide. I have just made the config reset/generate on launch for easy testing so this config doesn’t slow me down much. Is there anyway to make the client not have this problem when having new settings/hacks? Possibly once the client start it checks if it needs to write any new hacks/settings to the config. I tried to do this but failed because of my lack of java skill.

**Comment by Ace8Underscore** [comment]
Other than those issues this is a great client and am thinking of contributing to it :D. Great work!

**Comment by GishReloaded** [comment]
It is should to make a function that will be called before loading data from the config. It will compare the hacks that are in the config with those that your client downloaded, if hack not found, add new lines to the config. Thanks you for issue. It will be fixed in the next update.
