### ISSUE TITLE
Lack of the necessary module SafeWalk.. Add?

### ISSUE THREAD

**Issue by xCoDiS** [GishReloaded/Gish-Code-1.12.2#3]
Hello, a good cheat for minecraft but I would like to add a safewalk, and a bypass of popular anti-cheats matrix and reflexes. 
Successful development!

**Comment by xCoDiS** [comment]
Another function InventoryWalk, InvManager!

Not a new feature, but pretty useful for any player. An example of a walk in the inventory, sorting things. You can also add cheats to sort things or dump garbage (hunger games)

**Comment by GishReloaded** [comment]
Nice functions. I will try to add this.
